-- H2 的 DATETIME 默认保留 6 位小数，MySQL 默认 0 位；仅为 H2 测试对齐精度。
-- 仍先执行真实 schema.sql，保留数据库默认值、可空性和 ON UPDATE 行为。
ALTER TABLE hub_user ALTER COLUMN create_time DATETIME(0) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE hub_user ALTER COLUMN update_time DATETIME(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE hub_image ALTER COLUMN create_time DATETIME(0) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE hub_image ALTER COLUMN update_time DATETIME(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
